FEW_NERD_COARSE_DISJOINT = {
    "event": "disjoint/event",
    "person": "disjoint/person", 
    "art": "disjoint/art",
    "building": "disjoint/building",
    "location": "disjoint/location",
    "organization":"disjoint/organization",
    "product": "disjoint/product", 
    "other": "disjoint/other"
}

FEW_NERD_COARSE_JOINT = {
    "event": "joint/event",
    "person": "joint/person", 
    "art": "joint/art",
    "building": "joint/building",
    "location": "joint/location",
    "organization":"joint/organization",
    "product": "joint/product", 
    "other": "joint/other"
}

FEW_NERD_FINE_DISJOINT = {
    "art-film": "disjoint/art-film",
    "product-train": "disjoint/product-train",
    "other-livingthing": "disjoint/other-livingthing",
    "art-writtenart": "disjoint/art-writtenart",
    "building-theater": "disjoint/building-theater",
    "person-actor": "disjoint/person-actor",
    "organization-sportsleague": "disjoint/organization-sportsleague",
    "person-soldier": "disjoint/person-soldier",
    "other-god": "disjoint/other-god",
    "location-island": "disjoint/location-island",
    "event-attack,battle,war,militaryconflict": "disjoint/event-attack,battle,war,militaryconflict",
    "organization-media,newspaper": "disjoint/organization-media,newspaper",
    "building-restaurant": "disjoint/building-restaurant",
    "other-astronomything": "disjoint/other-astronomything",
    "organization-government,governmentagency": "disjoint/organization-government,governmentagency",
    "location-GPE": "disjoint/location-GPE",
    "event-sportsevent": "disjoint/event-sportsevent",
    "building-airport": "disjoint/building-airport",
    "product-car": "disjoint/product-car",
    "other-disease": "disjoint/other-disease",
    "location-mountain": "disjoint/location-mountain",
    "product-ship": "disjoint/product-ship",
    "building-other": "disjoint/building-other",
    "building-hotel": "disjoint/building-hotel",
    "organization-showorganization": "disjoint/organization-showorganization",
    "organization-politicalparty": "disjoint/organization-politicalparty",
    "event-other": "disjoint/event-other",
    "building-sportsfacility": "disjoint/building-sportsfacility",
    "product-food": "disjoint/product-food",
    "other-medical": "disjoint/other-medical",
    "organization-sportsteam": "disjoint/organization-sportsteam",
    "person-other": "disjoint/person-other",
    "location-road,railway,highway,transit": "disjoint/location-road,railway,highway,transit",   
    "other-award": "disjoint/other-award",
    "other-chemicalthing": "disjoint/other-chemicalthing",
    "other-law": "disjoint/other-law",
    "art-music": "disjoint/art-music",
    "product-other": "disjoint/product-other",
    "other-language": "disjoint/other-language",
    "location-bodiesofwater": "disjoint/location-bodiesofwater",
    "organization-other": "disjoint/organization-other",
    "product-airplane": "disjoint/product-airplane",
    "building-library": "disjoint/building-library",
    "organization-religion": "disjoint/organization-religion",
    "art-broadcastprogram": "disjoint/art-broadcastprogram",
    "person-scholar": "disjoint/person-scholar",
    "person-athlete": "disjoint/person-athlete",
    "other-currency": "disjoint/other-currency",
    "location-other": "disjoint/location-other",
    "person-director": "disjoint/person-director",
    "product-game": "disjoint/product-game",
    "building-hospital": "disjoint/building-hospital",
    "event-protest": "disjoint/event-protest",
    "event-election": "disjoint/event-election",
    "other-educationaldegree": "disjoint/other-educationaldegree",
    "art-other": "disjoint/art-other",
    "art-painting": "disjoint/art-painting",
    "organization-company": "disjoint/organization-company",
    "product-weapon": "disjoint/product-weapon",
    "event-disaster": "disjoint/event-disaster",
    "organization-education": "disjoint/organization-education",
    "product-software": "disjoint/product-software",
    "person-artist,author": "disjoint/person-artist,author",
    "location-park": "disjoint/location-park",
    "person-politician": "disjoint/person-politician",
    "other-biologything": "disjoint/other-biologything"
}

FEW_NERD_FINE_JOINT = {
    "art-film": "joint/art-film",
    "product-train": "joint/product-train",
    "other-livingthing": "joint/other-livingthing",
    "art-writtenart": "joint/art-writtenart",
    "building-theater": "joint/building-theater",
    "person-actor": "joint/person-actor",
    "organization-sportsleague": "joint/organization-sportsleague",
    "person-soldier": "joint/person-soldier",
    "other-god": "joint/other-god",
    "location-island": "joint/location-island",
    "event-attack,battle,war,militaryconflict": "joint/event-attack,battle,war,militaryconflict",
    "organization-media,newspaper": "joint/organization-media,newspaper",
    "building-restaurant": "joint/building-restaurant",
    "other-astronomything": "joint/other-astronomything",
    "organization-government,governmentagency": "joint/organization-government,governmentagency",
    "location-GPE": "joint/location-GPE",
    "event-sportsevent": "joint/event-sportsevent",
    "building-airport": "joint/building-airport",
    "product-car": "joint/product-car",
    "other-disease": "joint/other-disease",
    "location-mountain": "joint/location-mountain",
    "product-ship": "joint/product-ship",
    "building-other": "joint/building-other",
    "building-hotel": "joint/building-hotel",
    "organization-showorganization": "joint/organization-showorganization",
    "organization-politicalparty": "joint/organization-politicalparty",
    "event-other": "joint/event-other",
    "building-sportsfacility": "joint/building-sportsfacility",
    "product-food": "joint/product-food",
    "other-medical": "joint/other-medical",
    "organization-sportsteam": "joint/organization-sportsteam",
    "person-other": "joint/person-other",
    "location-road,railway,highway,transit": "joint/location-road,railway,highway,transit",   
    "other-award": "joint/other-award",
    "other-chemicalthing": "joint/other-chemicalthing",
    "other-law": "joint/other-law",
    "art-music": "joint/art-music",
    "product-other": "joint/product-other",
    "other-language": "joint/other-language",
    "location-bodiesofwater": "joint/location-bodiesofwater",
    "organization-other": "joint/organization-other",
    "product-airplane": "joint/product-airplane",
    "building-library": "joint/building-library",
    "organization-religion": "joint/organization-religion",
    "art-broadcastprogram": "joint/art-broadcastprogram",
    "person-scholar": "joint/person-scholar",
    "person-athlete": "joint/person-athlete",
    "other-currency": "joint/other-currency",
    "location-other": "joint/location-other",
    "person-director": "joint/person-director",
    "product-game": "joint/product-game",
    "building-hospital": "joint/building-hospital",
    "event-protest": "joint/event-protest",
    "event-election": "joint/event-election",
    "other-educationaldegree": "joint/other-educationaldegree",
    "art-other": "joint/art-other",
    "art-painting": "joint/art-painting",
    "organization-company": "joint/organization-company",
    "product-weapon": "joint/product-weapon",
    "event-disaster": "joint/event-disaster",
    "organization-education": "joint/organization-education",
    "product-software": "joint/product-software",
    "person-artist,author": "joint/person-artist,author",
    "location-park": "joint/location-park",
    "person-politician": "joint/person-politician",
    "other-biologything": "joint/other-biologything"
}

STACKOVERFLOW_DISJOINT = {
    'HTML_XML_Tag':'disjoint/HTML_XML_Tag',
    'Data_Structure':'disjoint/Data_Structure',
    'File_Name':'disjoint/File_Name',
    'Language':'disjoint/Language',
    'Device':'disjoint/Device',
    'Value':'disjoint/Value',
    'File_Type':'disjoint/File_Type',
    'Version':'disjoint/Version',
    'Data_Type':'disjoint/Data_Type',
    'Variable_Name':'disjoint/Variable_Name',
    'Library_Class':'disjoint/Library_Class',
    'Library_Variable':'disjoint/Library_Variable',
    'Class_Name':'disjoint/Class_Name',
    'Code_Block':'disjoint/Code_Block',
    'User_Interface_Element':'disjoint/User_Interface_Element',
    'Application':'disjoint/Application',
    'Library_Function':'disjoint/Library_Function',
    'Library':'disjoint/Library',
    'Operating_System':'disjoint/Operating_System'
}

STACKOVERFLOW_JOINT = {
    'HTML_XML_Tag':'joint/HTML_XML_Tag',
    'Data_Structure':'joint/Data_Structure',
    'File_Name':'joint/File_Name',
    'Language':'joint/Language',
    'Device':'joint/Device',
    'Value':'joint/Value',
    'File_Type':'joint/File_Type',
    'Version':'joint/Version',
    'Data_Type':'joint/Data_Type',
    'Variable_Name':'joint/Variable_Name',
    'Library_Class':'joint/Library_Class',
    'Library_Variable':'joint/Library_Variable',
    'Class_Name':'joint/Class_Name',
    'Code_Block':'joint/Code_Block',
    'User_Interface_Element':'joint/User_Interface_Element',
    'Application':'joint/Application',
    'Library_Function':'joint/Library_Function',
    'Library':'joint/Library',
    'Operating_System':'joint/Operating_System'
}

PROTOCOLS = {
    'CI coarse-few-nerd': FEW_NERD_COARSE_DISJOINT,
    'CI fine-few-nerd': FEW_NERD_FINE_DISJOINT,
    'CI stackoverflow': STACKOVERFLOW_DISJOINT,
    'online coarse-few-nerd': FEW_NERD_COARSE_JOINT,
    'online fine-few-nerd': FEW_NERD_FINE_JOINT,
    'online stackoverflow': STACKOVERFLOW_JOINT,
    'multi-task coarse-few-nerd': FEW_NERD_COARSE_DISJOINT,
    'multi-task fine-few-nerd': FEW_NERD_FINE_DISJOINT,
    'multi-task stackoverflow': STACKOVERFLOW_DISJOINT
}

if __name__ == '__main__':
    print(';'.join(list(PROTOCOLS['fine-tune-fine few-nerd'].keys())))