FEW_NERD_COARSE_DISJOINT = {
    "event": "continual/coarse/disjoint/event",
    "person": "continual/coarse/disjoint/person", 
    "art": "continual/coarse/disjoint/art",
    "building": "continual/coarse/disjoint/building",
    "location": "continual/coarse/disjoint/location",
    "organization":"continual/coarse/disjoint/organization",
    "product": "continual/coarse/disjoint/product", 
    "other": "continual/coarse/disjoint/other"
}

FEW_NERD_COARSE_JOINT = {
    "event": "continual/coarse/joint/event",
    "person": "continual/coarse/joint/person", 
    "art": "continual/coarse/joint/art",
    "building": "continual/coarse/joint/building",
    "location": "continual/coarse/joint/location",
    "organization":"continual/coarse/joint/organization",
    "product": "continual/coarse/joint/product", 
    "other": "continual/coarse/joint/other"
}

FEW_NERD_FINE_DISJOINT = {
    "art-film": "continual/coarse/disjoint/art-film",
    "product-train": "continual/coarse/disjoint/product-train",
    "other-livingthing": "continual/coarse/disjoint/other-livingthing",
    "art-writtenart": "continual/coarse/disjoint/art-writtenart",
    "building-theater": "continual/coarse/disjoint/building-theater",
    "person-actor": "continual/coarse/disjoint/person-actor",
    "organization-sportsleague": "continual/coarse/disjoint/organization-sportsleague",
    "person-soldier": "continual/coarse/disjoint/person-soldier",
    "other-god": "continual/coarse/disjoint/other-god",
    "location-island": "continual/coarse/disjoint/location-island",
    "event-attack,battle,war,militaryconflict": "continual/coarse/disjoint/event-attack,battle,war,militaryconflict",
    "organization-media,newspaper": "continual/coarse/disjoint/organization-media,newspaper",
    "building-restaurant": "continual/coarse/disjoint/building-restaurant",
    "other-astronomything": "continual/coarse/disjoint/other-astronomything",
    "organization-government,governmentagency": "continual/coarse/disjoint/organization-government,governmentagency",
    "location-GPE": "continual/coarse/disjoint/location-GPE",
    "event-sportsevent": "continual/coarse/disjoint/event-sportsevent",
    "building-airport": "continual/coarse/disjoint/building-airport",
    "product-car": "continual/coarse/disjoint/product-car",
    "other-disease": "continual/coarse/disjoint/other-disease",
    "location-mountain": "continual/coarse/disjoint/location-mountain",
    "product-ship": "continual/coarse/disjoint/product-ship",
    "building-other": "continual/coarse/disjoint/building-other",
    "building-hotel": "continual/coarse/disjoint/building-hotel",
    "organization-showorganization": "continual/coarse/disjoint/organization-showorganization",
    "organization-politicalparty": "continual/coarse/disjoint/organization-politicalparty",
    "event-other": "continual/coarse/disjoint/event-other",
    "building-sportsfacility": "continual/coarse/disjoint/building-sportsfacility",
    "product-food": "continual/coarse/disjoint/product-food",
    "other-medical": "continual/coarse/disjoint/other-medical",
    "organization-sportsteam": "continual/coarse/disjoint/organization-sportsteam",
    "person-other": "continual/coarse/disjoint/person-other",
    "location-road,railway,highway,transit": "continual/coarse/disjoint/location-road,railway,highway,transit",   
    "other-award": "continual/coarse/disjoint/other-award",
    "other-chemicalthing": "continual/coarse/disjoint/other-chemicalthing",
    "other-law": "continual/coarse/disjoint/other-law",
    "art-music": "continual/coarse/disjoint/art-music",
    "product-other": "continual/coarse/disjoint/product-other",
    "other-language": "continual/coarse/disjoint/other-language",
    "location-bodiesofwater": "continual/coarse/disjoint/location-bodiesofwater",
    "organization-other": "continual/coarse/disjoint/organization-other",
    "product-airplane": "continual/coarse/disjoint/product-airplane",
    "building-library": "continual/coarse/disjoint/building-library",
    "organization-religion": "continual/coarse/disjoint/organization-religion",
    "art-broadcastprogram": "continual/coarse/disjoint/art-broadcastprogram",
    "person-scholar": "continual/coarse/disjoint/person-scholar",
    "person-athlete": "continual/coarse/disjoint/person-athlete",
    "other-currency": "continual/coarse/disjoint/other-currency",
    "location-other": "continual/coarse/disjoint/location-other",
    "person-director": "continual/coarse/disjoint/person-director",
    "product-game": "continual/coarse/disjoint/product-game",
    "building-hospital": "continual/coarse/disjoint/building-hospital",
    "event-protest": "continual/coarse/disjoint/event-protest",
    "event-election": "continual/coarse/disjoint/event-election",
    "other-educationaldegree": "continual/coarse/disjoint/other-educationaldegree",
    "art-other": "continual/coarse/disjoint/art-other",
    "art-painting": "continual/coarse/disjoint/art-painting",
    "organization-company": "continual/coarse/disjoint/organization-company",
    "product-weapon": "continual/coarse/disjoint/product-weapon",
    "event-disaster": "continual/coarse/disjoint/event-disaster",
    "organization-education": "continual/coarse/disjoint/organization-education",
    "product-software": "continual/coarse/disjoint/product-software",
    "person-artist,author": "continual/coarse/disjoint/person-artist,author",
    "location-park": "continual/coarse/disjoint/location-park",
    "person-politician": "continual/coarse/disjoint/person-politician",
    "other-biologything": "continual/coarse/disjoint/other-biologything"
}

STACKOVERFLOW_DISJOINT = {
    'HTML_XML_Tag':'continual/disjoint/HTML_XML_Tag',
    'Data_Structure':'continual/disjoint/Data_Structure',
    'User_Name':'continual/disjoint/User_Name',
    'File_Name':'continual/disjoint/File_Name',
    'Language':'continual/disjoint/Language',
    'Device':'continual/disjoint/Device',
    'Value':'continual/disjoint/Value',
    'File_Type':'continual/disjoint/File_Type',
    'Keyboard_IP':'continual/disjoint/Keyboard_IP',
    'Version':'continual/disjoint/Version',
    'Website':'continual/disjoint/Website',
    'Data_Type':'continual/disjoint/Data_Type',
    'Error_Name':'continual/disjoint/Error_Name',
    'Algorithm':'continual/disjoint/Algorithm',
    'Organization':'continual/disjoint/Organization',
    'Variable_Name':'continual/disjoint/Variable_Name',
    'Library_Class':'continual/disjoint/Library_Class',
    'Library_Variable':'continual/disjoint/Library_Variable',
    'Class_Name':'continual/disjoint/Class_Name',
    'Code_Block':'continual/disjoint/Code_Block',
    'Function_Name':'continual/disjoint/Function_Name',
    'User_Interface_Element':'continual/disjoint/User_Interface_Element',
    'Output_Block':'continual/disjoint/Output_Block',
    'Application':'continual/disjoint/Application',
    'Library_Function':'continual/disjoint/Library_Function',
    'Library':'continual/disjoint/Library',
    'Operating_System':'continual/disjoint/Operating_System'
}

PROTOCOLS = {
    'fine-tune few-nerd': FEW_NERD_COARSE_DISJOINT,
    'fine-tune stackoverflow': STACKOVERFLOW_DISJOINT,
    'multi-task few-nerd': FEW_NERD_COARSE_DISJOINT
}