FEW_NERD_COARSE_DISJOINT = {
    "event": "disjoint/event",
    "person": "disjoint/person", 
    "art": "disjoint/art",
    "building": "disjoint/building",
    "location": "disjoint/location",
    "organization":"disjoint/organization",
    "product": "disjoint/product", 
    "other": "disjoint/other"
}

FEW_NERD_COARSE_JOINT = {
    "event": "joint/event",
    "person": "joint/person", 
    "art": "joint/art",
    "building": "joint/building",
    "location": "joint/location",
    "organization":"joint/organization",
    "product": "joint/product", 
    "other": "joint/other"
}

FEW_NERD_FINE_DISJOINT = {
    "art-film": "disjoint/art-film",
    "product-train": "disjoint/product-train",
    "other-livingthing": "disjoint/other-livingthing",
    "art-writtenart": "disjoint/art-writtenart",
    "building-theater": "disjoint/building-theater",
    "person-actor": "disjoint/person-actor",
    "organization-sportsleague": "disjoint/organization-sportsleague",
    "person-soldier": "disjoint/person-soldier",
    "other-god": "disjoint/other-god",
    "location-island": "disjoint/location-island",
    "event-attack,battle,war,militaryconflict": "disjoint/event-attack,battle,war,militaryconflict",
    "organization-media,newspaper": "disjoint/organization-media,newspaper",
    "building-restaurant": "disjoint/building-restaurant",
    "other-astronomything": "disjoint/other-astronomything",
    "organization-government,governmentagency": "disjoint/organization-government,governmentagency",
    "location-GPE": "disjoint/location-GPE",
    "event-sportsevent": "disjoint/event-sportsevent",
    "building-airport": "disjoint/building-airport",
    "product-car": "disjoint/product-car",
    "other-disease": "disjoint/other-disease",
    "location-mountain": "disjoint/location-mountain",
    "product-ship": "disjoint/product-ship",
    "building-other": "disjoint/building-other",
    "building-hotel": "disjoint/building-hotel",
    "organization-showorganization": "disjoint/organization-showorganization",
    "organization-politicalparty": "disjoint/organization-politicalparty",
    "event-other": "disjoint/event-other",
    "building-sportsfacility": "disjoint/building-sportsfacility",
    "product-food": "disjoint/product-food",
    "other-medical": "disjoint/other-medical",
    "organization-sportsteam": "disjoint/organization-sportsteam",
    "person-other": "disjoint/person-other",
    "location-road,railway,highway,transit": "disjoint/location-road,railway,highway,transit",   
    "other-award": "disjoint/other-award",
    "other-chemicalthing": "disjoint/other-chemicalthing",
    "other-law": "disjoint/other-law",
    "art-music": "disjoint/art-music",
    "product-other": "disjoint/product-other",
    "other-language": "disjoint/other-language",
    "location-bodiesofwater": "disjoint/location-bodiesofwater",
    "organization-other": "disjoint/organization-other",
    "product-airplane": "disjoint/product-airplane",
    "building-library": "disjoint/building-library",
    "organization-religion": "disjoint/organization-religion",
    "art-broadcastprogram": "disjoint/art-broadcastprogram",
    "person-scholar": "disjoint/person-scholar",
    "person-athlete": "disjoint/person-athlete",
    "other-currency": "disjoint/other-currency",
    "location-other": "disjoint/location-other",
    "person-director": "disjoint/person-director",
    "product-game": "disjoint/product-game",
    "building-hospital": "disjoint/building-hospital",
    "event-protest": "disjoint/event-protest",
    "event-election": "disjoint/event-election",
    "other-educationaldegree": "disjoint/other-educationaldegree",
    "art-other": "disjoint/art-other",
    "art-painting": "disjoint/art-painting",
    "organization-company": "disjoint/organization-company",
    "product-weapon": "disjoint/product-weapon",
    "event-disaster": "disjoint/event-disaster",
    "organization-education": "disjoint/organization-education",
    "product-software": "disjoint/product-software",
    "person-artist,author": "disjoint/person-artist,author",
    "location-park": "disjoint/location-park",
    "person-politician": "disjoint/person-politician",
    "other-biologything": "disjoint/other-biologything"
}

STACKOVERFLOW_DISJOINT = {
    'HTML_XML_Tag':'disjoint/HTML_XML_Tag',
    'Data_Structure':'disjoint/Data_Structure',
    # 'User_Name':'disjoint/User_Name',
    'File_Name':'disjoint/File_Name',
    'Language':'disjoint/Language',
    'Device':'disjoint/Device',
    'Value':'disjoint/Value',
    'File_Type':'disjoint/File_Type',
    # 'Keyboard_IP':'disjoint/Keyboard_IP',
    'Version':'disjoint/Version',
    # 'Website':'disjoint/Website',
    'Data_Type':'disjoint/Data_Type',
    # 'Error_Name':'disjoint/Error_Name',
    # 'Algorithm':'disjoint/Algorithm',
    # 'Organization':'disjoint/Organization',
    'Variable_Name':'disjoint/Variable_Name',
    'Library_Class':'disjoint/Library_Class',
    'Library_Variable':'disjoint/Library_Variable',
    'Class_Name':'disjoint/Class_Name',
    'Code_Block':'disjoint/Code_Block',
    # 'Function_Name':'disjoint/Function_Name',
    'User_Interface_Element':'disjoint/User_Interface_Element',
    # 'Output_Block':'disjoint/Output_Block',
    'Application':'disjoint/Application',
    'Library_Function':'disjoint/Library_Function',
    'Library':'disjoint/Library',
    'Operating_System':'disjoint/Operating_System'
}

PROTOCOLS = {
    'CI coarse-few-nerd': FEW_NERD_COARSE_DISJOINT,
    'CI fine-few-nerd': FEW_NERD_FINE_DISJOINT,
    'CI stackoverflow': STACKOVERFLOW_DISJOINT,
    'multi-task coarse-few-nerd': FEW_NERD_COARSE_DISJOINT,
    'multi-task fine-few-nerd': FEW_NERD_FINE_DISJOINT,
    'multi-task stackoverflow': STACKOVERFLOW_DISJOINT
}

if __name__ == '__main__':
    print(';'.join(list(PROTOCOLS['fine-tune-fine few-nerd'].keys())))